import { Check, Edit3, Search, ShieldOff } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { Button } from "../components/Button";
import { DataTable } from "../components/DataTable";
import { FilterField, FiltersBar } from "../components/FiltersBar";
import { PageHeader } from "../components/PageHeader";
import { api } from "../lib/api";
import { useAuth } from "../lib/auth";
import { EmployeeContract, EmployeeContractRecord } from "../lib/types";
import { useApi } from "../lib/useApi";

export function EmployeeContractsPage() {
  const { user } = useAuth(), isAdmin = Boolean(user?.roles.includes("ADMIN"));
  const records = useApi<EmployeeContractRecord[]>("/api/employees/contracts/all", []);
  const [search, setSearch] = useState(""), [employeeId, setEmployeeId] = useState(""), [startDate, setStartDate] = useState(""), [endDate, setEndDate] = useState(""), [contractType, setContractType] = useState(""), [reference, setReference] = useState(""), [note, setNote] = useState(""), [editingId, setEditingId] = useState<string | null>(null), [exemptReason, setExemptReason] = useState(""), [message, setMessage] = useState<string | null>(null), [error, setError] = useState<string | null>(null);
  const visible = useMemo(() => { const q = search.trim().toLowerCase(); return records.data.filter(row => !q || `${row.fullName} ${code(row)} ${row.department || ""}`.toLowerCase().includes(q)); }, [records.data, search]);
  const selected = records.data.find(row => row.id === employeeId);
  const contracts = visible.flatMap(employee => employee.contracts.map(contract => ({ employee, contract })));
  function clear() { setStartDate(""); setEndDate(""); setContractType(""); setReference(""); setNote(""); setEditingId(null); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); if (!employeeId || !startDate) return setError("Employé et date de début sont obligatoires."); try { await api(editingId ? `/api/employees/contracts/${editingId}` : "/api/employees/contracts", { method: editingId ? "PATCH" : "POST", body: JSON.stringify({ employeeId, startDate, endDate: endDate || undefined, contractType, reference, note }) }); setMessage(editingId ? "Contrat modifié." : "Contrat ajouté."); clear(); records.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Enregistrement impossible."); } }
  function edit(contract: EmployeeContract) { setEmployeeId(contract.employeeId); setStartDate(contract.startDate.slice(0, 10)); setEndDate(contract.endDate?.slice(0, 10) || ""); setContractType(contract.contractType || ""); setReference(contract.reference || ""); setNote(contract.note || ""); setEditingId(contract.id); }
  async function toggleExemption() { if (!selected) return; setError(null); try { await api(`/api/employees/${selected.id}/attendance-exemption`, { method: "PATCH", body: JSON.stringify({ exempt: !selected.attendanceTrackingExempt, reason: !selected.attendanceTrackingExempt ? exemptReason : undefined }) }); setMessage(selected.attendanceTrackingExempt ? "Suivi de présence réactivé." : "Employé exclu du suivi de présence."); setExemptReason(""); records.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Action impossible."); } }
  return <><PageHeader title="Contrats employés" /><section className="panel"><div className="alert">Les jours avant le début du contrat sont marqués DC. Les jours après sa fin sont marqués EC et ne comptent jamais comme absence.</div><FiltersBar onReset={() => { setSearch(""); setEmployeeId(""); clear(); }}><FilterField label="Recherche"><div className="input-icon"><Search size={15}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Nom, matricule..." /></div></FilterField><FilterField label="Employé"><select value={employeeId} onChange={e => { setEmployeeId(e.target.value); setExemptReason(""); }}><option value="">Choisir...</option>{visible.map(row => <option key={row.id} value={row.id}>{code(row)} - {row.fullName}</option>)}</select></FilterField></FiltersBar>{message && <div className="alert alert-success">{message}</div>}{error && <div className="alert alert-error">{error}</div>}
  {isAdmin && selected && <div className={`contract-exemption-card ${selected.attendanceTrackingExempt ? "active" : ""}`}><div><strong><ShieldOff size={16}/> Exception haute responsabilité</strong><span>{selected.attendanceTrackingExempt ? `Suivi désactivé — ${selected.attendanceExemptReason}` : "L'employé est actuellement suivi normalement."}</span></div>{!selected.attendanceTrackingExempt && <input value={exemptReason} onChange={e => setExemptReason(e.target.value)} placeholder="Motif obligatoire..." />}<Button variant={selected.attendanceTrackingExempt ? "secondary" : "danger"} onClick={toggleExemption}>{selected.attendanceTrackingExempt ? "Réactiver le suivi" : "Exclure du suivi"}</Button></div>}
  <form className="quick-create contract-form" onSubmit={submit}><strong>{editingId ? "Modifier le contrat" : "Nouveau contrat"}</strong><label><span>Début</span><input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} /></label><label><span>Fin (facultative)</span><input type="date" value={endDate} onChange={e => setEndDate(e.target.value)} /></label><label><span>Type</span><input value={contractType} onChange={e => setContractType(e.target.value)} placeholder="CDI, CDD..." /></label><label><span>Référence</span><input value={reference} onChange={e => setReference(e.target.value)} /></label><label><span>Note</span><input value={note} onChange={e => setNote(e.target.value)} /></label><Button variant="primary" type="submit"><Check size={15}/>{editingId ? "Enregistrer" : "Ajouter"}</Button>{editingId && <Button variant="secondary" type="button" onClick={clear}>Annuler</Button>}</form>
  <div className="panel-header"><h2>Historique des contrats</h2><span className="muted">{contracts.length} contrat(s)</span></div><DataTable rows={contracts} pageSize={40} empty="Aucun contrat enregistré." columns={[{key:"employee",header:"Employé",render:row=><div className="table-main-cell"><strong>{row.employee.fullName}</strong><span>{code(row.employee)}</span></div>,sortValue:row=>row.employee.fullName},{key:"department",header:"Département",render:row=>row.employee.department||"-"},{key:"start",header:"Début",render:row=>date(row.contract.startDate),sortValue:row=>row.contract.startDate},{key:"end",header:"Fin",render:row=>row.contract.endDate?date(row.contract.endDate):"Sans fin",sortValue:row=>row.contract.endDate||"9999"},{key:"type",header:"Type / référence",render:row=><div className="table-main-cell"><strong>{row.contract.contractType||"-"}</strong><span>{row.contract.reference||"-"}</span></div>},{key:"status",header:"Statut",render:row=><span className={`badge ${contractStatus(row.contract)==="En cours"?"badge-green":contractStatus(row.contract)==="À venir"?"badge-blue":"badge-gray"}`}>{contractStatus(row.contract)}</span>},{key:"actions",header:"Actions",render:row=><Button variant="secondary" onClick={()=>edit(row.contract)}><Edit3 size={14}/>Modifier</Button>}]}/></section></>;
}
function code(row: { localMatricule?: string|null; biotimeCode?: string|null; employeeCode: string }) { return row.localMatricule || row.biotimeCode || row.employeeCode; }
function date(value: string) { return new Date(value).toLocaleDateString("fr-FR"); }
function contractStatus(row: EmployeeContract) { const today = new Date().toISOString().slice(0,10), start=row.startDate.slice(0,10), end=row.endDate?.slice(0,10); return today < start ? "À venir" : end && today > end ? "Terminé" : "En cours"; }
