import { Building2, Check, ChevronLeft, ChevronRight, FileText, Search, UserRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "../components/Button";
import { LoadingState } from "../components/LoadingState";
import { PageHeader } from "../components/PageHeader";
import { api } from "../lib/api";
import { Employee, JobCompany, JobPosition } from "../lib/types";
import { useApi } from "../lib/useApi";

type Source = { employee: any; sap: { company: string; jobTitle: string } | null; organization: { unit: string | null; subUnit: string | null; group: string | null } };

export function JobDescriptionWizardPage() {
  const navigate = useNavigate();
  const employees = useApi<Employee[]>("/api/employees", []);
  const companies = useApi<JobCompany[]>("/api/job-descriptions/companies", []);
  const positions = useApi<JobPosition[]>("/api/job-descriptions/positions", []);
  const [step, setStep] = useState(1); const [search, setSearch] = useState(""); const [employeeId, setEmployeeId] = useState(""); const [source, setSource] = useState<Source | null>(null); const [companyId, setCompanyId] = useState(""); const [positionId, setPositionId] = useState(""); const [templateId, setTemplateId] = useState(""); const [title, setTitle] = useState(""); const [managerName, setManagerName] = useState(""); const [managerJobTitle, setManagerJobTitle] = useState(""); const [effectiveDate, setEffectiveDate] = useState(new Date().toISOString().slice(0, 10)); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const activeEmployees = useMemo(() => employees.data.filter(row => row.status === "ACTIVE" && (!search.trim() || `${row.fullName} ${row.localMatricule || ""} ${row.employeeCode}`.toLowerCase().includes(search.toLowerCase()))).slice(0, 80), [employees.data, search]);
  const availablePositions = positions.data.filter(row => row.isActive && (!row.companyId || row.companyId === companyId));
  const position = positions.data.find(row => row.id === positionId) || null;
  const employee = employees.data.find(row => row.id === employeeId) || null;

  useEffect(() => { if (!employeeId) return; api<Source>(`/api/job-descriptions/employee-source/${employeeId}`).then(value => { setSource(value); setTitle(value.sap?.jobTitle || ""); const company = companies.data.find(row => row.code === value.sap?.company || row.code === value.organization.unit); if (company) setCompanyId(company.id); const normalized = value.sap?.jobTitle?.trim().toLowerCase(); const match = positions.data.find(row => row.title.toLowerCase() === normalized || row.aliases.some(alias => alias.sourceValue.toLowerCase() === normalized)); if (match) { setPositionId(match.id); setTemplateId(match.templates.find(item => item.currentVersion?.status === "VALIDATED")?.id || match.templates[0]?.id || ""); setTitle(match.title); } }).catch(reason => setError(reason instanceof Error ? reason.message : "Lecture employé impossible.")); }, [employeeId, companies.data, positions.data]);
  useEffect(() => { if (!position) return; setTitle(position.title); if (!position.templates.some(row => row.id === templateId)) setTemplateId(position.templates.find(row => row.currentVersion?.status === "VALIDATED")?.id || position.templates[0]?.id || ""); }, [positionId]);

  function next() { const issue = step === 1 && !employeeId ? "Sélectionnez un employé." : step === 2 && !companyId ? "Sélectionnez une société." : step === 3 && !title.trim() ? "Le poste est obligatoire." : null; if (issue) return setError(issue); setError(null); setStep(value => Math.min(5, value + 1)); }
  async function create() { if (!employeeId || !companyId || !title.trim()) return; setSaving(true); try { const result = await api<{ id: string }>("/api/job-descriptions/documents", { method: "POST", body: JSON.stringify({ employeeId, companyId, jobPositionId: positionId || undefined, templateId: templateId || undefined, selectedJobTitle: title, managerName, managerJobTitle, effectiveDate }) }); navigate(`/job-descriptions/documents/${result.id}/builder`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Création impossible."); } finally { setSaving(false); } }

  if (employees.loading || companies.loading || positions.loading) return <LoadingState label="Préparation de l'assistant..." />;
  return <><PageHeader title="Nouvelle fiche de poste" backTo="/job-descriptions" backLabel="Bibliothèque" /><section className="panel job-wizard"><div className="job-wizard-steps">{["Employé", "Société", "Poste & modèle", "Informations", "Récapitulatif"].map((label, index) => <div className={`${step === index + 1 ? "active" : ""} ${step > index + 1 ? "done" : ""}`} key={label}><b>{step > index + 1 ? <Check size={14} /> : index + 1}</b><span>{label}</span></div>)}</div>{error && <div className="alert alert-error">{clean(error)}</div>}<div className="job-wizard-body">
    {step === 1 && <section><h2><UserRound size={20} /> Choisir l'employé</h2><p>Les informations RH et le poste SAP seront récupérés automatiquement.</p><div className="input-icon"><Search size={15} /><input autoFocus value={search} onChange={event => setSearch(event.target.value)} placeholder="Nom, matricule..." /></div><div className="wizard-employee-grid">{activeEmployees.map(row => <button key={row.id} className={employeeId === row.id ? "selected" : ""} onClick={() => setEmployeeId(row.id)}><strong>{row.fullName}</strong><span>{row.localMatricule || row.employeeCode}</span><small>{row.department || "Sans département"}</small></button>)}</div></section>}
    {step === 2 && <section><h2><Building2 size={20} /> Société documentaire</h2><p>La société SAP est proposée automatiquement, mais reste modifiable selon vos droits.</p><div className="wizard-choice-grid">{companies.data.filter(row => row.isActive).map(row => <button key={row.id} className={companyId === row.id ? "selected" : ""} style={{ borderTopColor: row.primaryColor || "#0f766e" }} onClick={() => setCompanyId(row.id)}><b>{row.shortName}</b><span>{row.officialName}</span>{source?.sap?.company === row.code && <small>Proposée depuis SAP</small>}</button>)}</div></section>}
    {step === 3 && <section><h2><FileText size={20} /> Poste et modèle</h2><p>Le poste SAP est conservé dans le snapshot même si vous adaptez l'intitulé pour cette fiche.</p><div className="job-form-grid"><label className="filter-field"><span>Poste normalisé</span><select value={positionId} onChange={event => setPositionId(event.target.value)}><option value="">Poste personnalisé</option>{availablePositions.map(row => <option key={row.id} value={row.id}>{row.code} — {row.title}</option>)}</select></label><label className="filter-field"><span>Intitulé retenu</span><input value={title} onChange={event => setTitle(event.target.value)} /></label><label className="filter-field"><span>Template</span><select value={templateId} onChange={event => setTemplateId(event.target.value)}><option value="">Fiche vide</option>{position?.templates.filter(row => row.isActive).map(row => <option key={row.id} value={row.id}>{row.name} · {row.currentVersion?.status || "DRAFT"}</option>)}</select></label></div><div className="wizard-sap-note"><strong>Source SAP</strong><span>{source?.sap?.jobTitle || "Poste SAP absent"}</span></div></section>}
    {step === 4 && <section><h2>Informations de la fiche</h2><div className="job-form-grid"><label className="filter-field"><span>Date d'effet</span><input type="date" value={effectiveDate} onChange={event => setEffectiveDate(event.target.value)} /></label><label className="filter-field"><span>Responsable hiérarchique</span><input value={managerName} onChange={event => setManagerName(event.target.value)} /></label><label className="filter-field"><span>Fonction du responsable</span><input value={managerJobTitle} onChange={event => setManagerJobTitle(event.target.value)} /></label></div><p className="wizard-hint">Après création, le Builder s'ouvrira pour personnaliser les missions, KPI et blocs sans modifier le template source.</p></section>}
    {step === 5 && <section><h2>Récapitulatif avant création</h2><dl className="wizard-summary"><div><dt>Employé</dt><dd>{employee?.fullName}</dd></div><div><dt>Matricule</dt><dd>{employee?.localMatricule || employee?.employeeCode}</dd></div><div><dt>Société</dt><dd>{companies.data.find(row => row.id === companyId)?.shortName}</dd></div><div><dt>Poste SAP</dt><dd>{source?.sap?.jobTitle || "-"}</dd></div><div><dt>Poste retenu</dt><dd>{title}</dd></div><div><dt>Template</dt><dd>{position?.templates.find(row => row.id === templateId)?.name || "Fiche vide"}</dd></div><div><dt>Date d'effet</dt><dd>{new Date(`${effectiveDate}T00:00:00`).toLocaleDateString("fr-FR")}</dd></div><div><dt>Étape suivante</dt><dd>Personnalisation dans le Builder</dd></div></dl></section>}
  </div><footer className="job-wizard-actions"><Button variant="ghost" disabled={step === 1 || saving} onClick={() => setStep(value => value - 1)}><ChevronLeft size={15} /> Précédent</Button>{step < 5 ? <Button variant="primary" onClick={next}>Suivant <ChevronRight size={15} /></Button> : <Button variant="primary" disabled={saving} onClick={create}><Check size={15} /> {saving ? "Création..." : "Créer & personnaliser"}</Button>}</footer></section></>;
}

function clean(value: string) { try { const body = JSON.parse(value); return Array.isArray(body.message) ? body.message.join(" · ") : body.message || value; } catch { return value; } }
