import { Check, Plus, ShieldCheck, Trash2, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "../components/Button";
import { DataTable } from "../components/DataTable";
import { PageHeader } from "../components/PageHeader";
import { StatusBadge } from "../components/StatusBadge";
import { api } from "../lib/api";
import { useAuth } from "../lib/auth";
import { JobCompany } from "../lib/types";
import { useApi } from "../lib/useApi";

type WorkflowStep = { id?: string; stepOrder: number; label: string; approverType: "ROLE" | "USER" | "MANAGER"; approverRoleCode?: string; approverUserId?: string; signatureRequired: boolean; stampRequired: boolean };
type Workflow = { id: string; name: string; companyId: string | null; company: JobCompany | null; isActive: boolean; steps: WorkflowStep[] };
type Approvers = { users: Array<{ id: string; fullName: string; username: string; roles: string[] }>; roles: Array<{ code: string; name: string }> };
type ApprovalRow = { id: string; createdAt: string; workflowStep: WorkflowStep; version: { id: string; description: { id: string; reference: string; employee: { fullName: string; localMatricule?: string | null }; company: JobCompany; jobPosition: { title: string } | null; createdBy: { fullName: string } }; approvals: Array<{ id: string; status: string; workflowStep: WorkflowStep }> } };

export function JobDescriptionWorkflowPage() {
  const { can } = useAuth();
  const [tab, setTab] = useState<"queue" | "workflows">("queue");
  const queue = useApi<ApprovalRow[]>(can("job_description.validate") ? "/api/job-descriptions/validation-queue" : null, []);
  const workflows = useApi<Workflow[]>("/api/job-descriptions/workflows", []);
  const companies = useApi<JobCompany[]>("/api/job-descriptions/companies", []);
  const approvers = useApi<Approvers>(can("job_template.manage") ? "/api/job-descriptions/workflow-approvers" : null, { users: [], roles: [] });
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [review, setReview] = useState<{ row: ApprovalRow; action: "approve" | "reject"; comment: string } | null>(null);
  const [creating, setCreating] = useState(false);

  function reload() { queue.reload(); workflows.reload(); }
  async function confirmReview() { if (!review || review.action === "reject" && !review.comment.trim()) return; try { await api(`/api/job-descriptions/approvals/${review.row.id}/${review.action}`, { method: "POST", body: JSON.stringify({ comment: review.comment }) }); setMessage(review.action === "approve" ? "Étape approuvée." : "Fiche refusée et renvoyée à l'auteur."); setError(null); setReview(null); reload(); } catch (reason) { setError(cleanError(reason)); } }

  return <><PageHeader title="Validation des fiches de poste" backTo="/job-descriptions" backLabel="Bibliothèque" actions={<Link className="btn btn-secondary" to="/job-descriptions"><ShieldCheck size={15} /> Bibliothèque</Link>} /><section className="panel"><div className="tabs"><button className={tab === "queue" ? "active" : ""} onClick={() => setTab("queue")}>À valider ({queue.data.length})</button>{can("job_template.manage") && <button className={tab === "workflows" ? "active" : ""} onClick={() => setTab("workflows")}>Circuits de validation</button>}</div>{message && <div className="alert alert-success">{message}</div>}{error && <div className="alert alert-error">{error}</div>}
    {tab === "queue" ? <div className="stack"><div className="panel-header"><div><h2>Mes validations en attente</h2><span className="muted">Seule l'étape actuellement active est présentée à son validateur.</span></div></div><DataTable rows={queue.data} loading={queue.loading} empty="Aucune fiche de poste à valider." columns={[
      { key: "employee", header: "Employé", render: row => <div className="job-title-cell"><strong>{row.version.description.employee.fullName}</strong><span>{row.version.description.employee.localMatricule || "-"}</span></div>, sortValue: row => row.version.description.employee.fullName },
      { key: "reference", header: "Référence", render: row => <span className="job-code-chip">{row.version.description.reference}</span>, sortValue: row => row.version.description.reference },
      { key: "job", header: "Poste", render: row => row.version.description.jobPosition?.title || "Poste personnalisé" },
      { key: "company", header: "Société", render: row => row.version.description.company.shortName },
      { key: "step", header: "Étape active", render: row => <div className="workflow-step-label"><b>{row.workflowStep.stepOrder}</b><span>{row.workflowStep.label}</span></div> },
      { key: "author", header: "Créée par", render: row => row.version.description.createdBy.fullName },
      { key: "actions", header: "Actions", render: row => <div className="row-actions"><Link className="btn btn-ghost" to={`/job-descriptions/documents/${row.version.description.id}`}>Consulter</Link><Button variant="primary" onClick={() => setReview({ row, action: "approve", comment: "" })}><Check size={15} /> Approuver</Button><Button variant="danger" onClick={() => setReview({ row, action: "reject", comment: "" })}><X size={15} /> Rejeter</Button></div> }
    ]} /></div> : <div className="stack"><div className="panel-header"><div><h2>Circuits configurables</h2><span className="muted">Les étapes sont exécutées dans l'ordre. Admin conserve un droit de secours.</span></div><Button variant="primary" onClick={() => setCreating(true)}><Plus size={15} /> Nouveau circuit</Button></div><div className="workflow-card-grid">{workflows.data.map(workflow => <article key={workflow.id} className="workflow-card"><header><div><strong>{workflow.name}</strong><span>{workflow.company?.shortName || "Toutes sociétés"}</span></div><StatusBadge value={workflow.isActive ? "ACTIVE" : "ARCHIVED"} /></header><div className="workflow-timeline">{workflow.steps.map(step => <div key={step.id || step.stepOrder}><b>{step.stepOrder}</b><span><strong>{step.label}</strong><small>{step.approverType === "ROLE" ? `Rôle ${step.approverRoleCode}` : approvers.data.users.find(user => user.id === step.approverUserId)?.fullName || "Utilisateur"}</small></span>{step.signatureRequired && <i>Signature</i>}{step.stampRequired && <i>Cachet</i>}</div>)}</div></article>)}</div>{creating && <WorkflowEditor companies={companies.data} approvers={approvers.data} onClose={() => setCreating(false)} onCreated={() => { setCreating(false); setMessage("Circuit créé."); workflows.reload(); }} onError={setError} />}</div>}
  </section>{review && <div className="modal-backdrop"><div className="modal review-job-modal"><div className="modal-header"><div><span>{review.row.version.description.reference}</span><h2>{review.action === "approve" ? "Approuver cette étape" : "Rejeter la fiche"}</h2></div><button className="modal-close" onClick={() => setReview(null)}><X size={18} /></button></div><div className="modal-content"><p><strong>{review.row.version.description.employee.fullName}</strong> — {review.row.workflowStep.label}</p><label className="filter-field"><span>{review.action === "reject" ? "Motif obligatoire" : "Commentaire optionnel"}</span><textarea rows={5} autoFocus value={review.comment} onChange={event => setReview({ ...review, comment: event.target.value })} /></label><div className="job-editor-actions"><Button variant="ghost" onClick={() => setReview(null)}>Annuler</Button><Button variant={review.action === "approve" ? "primary" : "danger"} disabled={review.action === "reject" && !review.comment.trim()} onClick={confirmReview}>{review.action === "approve" ? "Confirmer l'approbation" : "Confirmer le rejet"}</Button></div></div></div></div>}</>;
}

function WorkflowEditor({ companies, approvers, onClose, onCreated, onError }: { companies: JobCompany[]; approvers: Approvers; onClose: () => void; onCreated: () => void; onError: (text: string) => void }) {
  const [name, setName] = useState(""); const [companyId, setCompanyId] = useState(""); const [steps, setSteps] = useState<WorkflowStep[]>([{ stepOrder: 1, label: "Validation DRH", approverType: "ROLE", approverRoleCode: "DRH", signatureRequired: false, stampRequired: false }]); const [saving, setSaving] = useState(false);
  function update(index: number, patch: Partial<WorkflowStep>) { setSteps(rows => rows.map((step, rowIndex) => rowIndex === index ? { ...step, ...patch } : step)); }
  function add() { setSteps(rows => [...rows, { stepOrder: rows.length + 1, label: "Nouvelle étape", approverType: "ROLE", approverRoleCode: "DRH", signatureRequired: false, stampRequired: false }]); }
  function remove(index: number) { setSteps(rows => rows.filter((_, rowIndex) => rowIndex !== index).map((step, rowIndex) => ({ ...step, stepOrder: rowIndex + 1 }))); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); try { await api("/api/job-descriptions/workflows", { method: "POST", body: JSON.stringify({ name, companyId: companyId || undefined, steps: steps.map(step => ({ ...step, approverRoleCode: step.approverType === "ROLE" ? step.approverRoleCode : undefined, approverUserId: step.approverType !== "ROLE" ? step.approverUserId : undefined })) }) }); onCreated(); } catch (reason) { onError(cleanError(reason)); } finally { setSaving(false); } }
  return <div className="modal-backdrop"><div className="modal workflow-editor-modal"><div className="modal-header"><div><span>Configuration</span><h2>Nouveau circuit de validation</h2></div><button className="modal-close" onClick={onClose}><X size={18} /></button></div><form className="modal-content stack" onSubmit={save}><div className="job-form-grid"><label className="filter-field"><span>Nom du circuit</span><input required value={name} onChange={event => setName(event.target.value)} placeholder="Responsable + DRH + DG" /></label><label className="filter-field"><span>Société</span><select value={companyId} onChange={event => setCompanyId(event.target.value)}><option value="">Toutes sociétés</option>{companies.map(row => <option key={row.id} value={row.id}>{row.shortName}</option>)}</select></label></div><div className="workflow-step-editor-list">{steps.map((step, index) => <div key={index}><b>{step.stepOrder}</b><input required value={step.label} onChange={event => update(index, { label: event.target.value })} /><select value={step.approverType} onChange={event => update(index, { approverType: event.target.value as WorkflowStep["approverType"], approverRoleCode: event.target.value === "ROLE" ? "DRH" : undefined, approverUserId: undefined })}><option value="ROLE">Par rôle</option><option value="USER">Utilisateur précis</option><option value="MANAGER">Responsable précis</option></select>{step.approverType === "ROLE" ? <select required value={step.approverRoleCode} onChange={event => update(index, { approverRoleCode: event.target.value })}>{approvers.roles.map(role => <option key={role.code} value={role.code}>{role.name}</option>)}</select> : <select required value={step.approverUserId || ""} onChange={event => update(index, { approverUserId: event.target.value })}><option value="">Choisir...</option>{approvers.users.map(user => <option key={user.id} value={user.id}>{user.fullName} ({user.username})</option>)}</select>}<label title="Signature requise"><input type="checkbox" checked={step.signatureRequired} onChange={event => update(index, { signatureRequired: event.target.checked })} /> Signature</label><label title="Cachet requis"><input type="checkbox" checked={step.stampRequired} onChange={event => update(index, { stampRequired: event.target.checked })} /> Cachet</label><button type="button" disabled={steps.length === 1} onClick={() => remove(index)}><Trash2 size={14} /></button></div>)}</div><Button type="button" variant="ghost" onClick={add}><Plus size={14} /> Ajouter une étape</Button><div className="job-editor-actions"><Button type="button" variant="ghost" onClick={onClose}>Annuler</Button><Button type="submit" variant="primary" disabled={saving}>{saving ? "Création..." : "Créer le circuit"}</Button></div></form></div></div>;
}
function cleanError(reason: unknown) { if (!(reason instanceof Error)) return "Opération impossible."; try { const parsed = JSON.parse(reason.message); return Array.isArray(parsed.message) ? parsed.message.join(" · ") : parsed.message || reason.message; } catch { return reason.message; } }
