import { AlertTriangle, CheckCircle2, FileUp, Upload } from "lucide-react";
import * as mammoth from "mammoth";
import { ChangeEvent, useState } from "react";
import { Button } from "../components/Button";
import { PageHeader } from "../components/PageHeader";
import { api } from "../lib/api";

type ImportItem = { companyCode?: string; jobCode: string; jobTitle: string; direction?: string; department?: string; service?: string; hierarchicalReporting?: string; mission?: string; missions?: string[]; responsibilities?: string[]; kpis?: string[]; profile?: string };
type Preview = { index: number; item: ImportItem; status: "CREATE" | "ADD_TEMPLATE" | "DUPLICATE" | "INVALID_COMPANY"; message: string };

export function JobDescriptionImportPage() {
  const [items, setItems] = useState<ImportItem[]>([]); const [preview, setPreview] = useState<Preview[]>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [result, setResult] = useState<string | null>(null);
  async function read(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setBusy(true); try { let rows: unknown[]; if (file.name.toLowerCase().endsWith(".docx")) { const extracted = await mammoth.extractRawText({ arrayBuffer: await file.arrayBuffer() }); rows = parseOrganizationManual(extracted.value); } else { const text = await file.text(); const parsed = file.name.toLowerCase().endsWith(".json") ? JSON.parse(text) : parseCsv(text); rows = Array.isArray(parsed) ? parsed : parsed.items; } if (!Array.isArray(rows) || !rows.length) throw new Error("Aucun poste structuré n'a été détecté dans ce fichier."); const normalized = rows.map(normalizeItem); setItems(normalized); setPreview([]); setResult(null); setError(null); const inspected = await api<Preview[]>("/api/job-descriptions/organization-import/preview", { method: "POST", body: JSON.stringify({ items: normalized }) }); setPreview(inspected); } catch (reason) { setError(reason instanceof Error ? reason.message : "Fichier illisible."); } finally { setBusy(false); event.target.value = ""; } }
  async function inspect() { setBusy(true); try { const rows = await api<Preview[]>("/api/job-descriptions/organization-import/preview", { method: "POST", body: JSON.stringify({ items }) }); setPreview(rows); setError(null); } catch (reason) { setError(clean(reason)); } finally { setBusy(false); } }
  async function commit() { setBusy(true); try { const response = await api<{ imported: number; skipped: number }>("/api/job-descriptions/organization-import/commit", { method: "POST", body: JSON.stringify({ items }) }); setResult(`${response.imported} modèle(s) importé(s), ${response.skipped} doublon(s) ignoré(s).`); setError(null); await inspect(); } catch (reason) { setError(clean(reason)); setBusy(false); } }
  const invalid = preview.some(row => row.status === "INVALID_COMPANY");
  return <><PageHeader title="Importer le Manuel d'Organisation" backTo="/job-descriptions" backLabel="Bibliothèque" /><section className="panel organization-import"><div className={`import-dropzone ${busy ? "is-loading" : ""}`}><FileUp size={30} /><div><strong>Déposez votre manuel Word</strong><span>Les postes, rattachements, missions, responsabilités, KPI et profils sont détectés automatiquement.</span></div><label className="btn btn-primary"><Upload size={15} /> {busy ? "Analyse..." : "Choisir le manuel"}<input hidden disabled={busy} type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document,.json,.csv" onChange={read} /></label></div><div className="import-auto-note"><CheckCircle2 size={18} /><div><strong>Aucune configuration nécessaire</strong><span>Les postes du manuel sont importés comme postes communs. Un aperçu anti-doublon reste obligatoire avant validation.</span></div></div>{error && <div className="alert alert-error">{error}</div>}{result && <div className="alert alert-success">{result}</div>}{items.length > 0 && <div className="import-toolbar"><span><b>{items.length}</b> poste(s) détecté(s)</span><Button variant="secondary" disabled={busy} onClick={inspect}>{busy ? "Analyse..." : "Ré-analyser"}</Button>{preview.length > 0 && <Button variant="primary" disabled={busy || invalid} onClick={commit}><Upload size={15} /> Importer les postes valides</Button>}</div>}{preview.length > 0 && <div className="import-preview-table"><table><thead><tr><th>N°</th><th>Portée</th><th>Code généré</th><th>Poste détecté</th><th>Résultat prévu</th></tr></thead><tbody>{preview.map(row => <tr key={row.index} className={row.status.toLowerCase()}><td>{row.index + 1}</td><td>{row.item.companyCode || "Toutes sociétés"}</td><td><span className="job-code-chip">{row.item.jobCode}</span></td><td><div className="import-job-cell"><strong>{row.item.jobTitle}</strong><small>{row.item.hierarchicalReporting ? `Rattaché à ${row.item.hierarchicalReporting}` : "Rattachement non indiqué"}</small></div></td><td><span>{row.status === "CREATE" || row.status === "ADD_TEMPLATE" ? <CheckCircle2 size={14} /> : <AlertTriangle size={14} />}{label(row.status)}</span><small>{row.message}</small></td></tr>)}</tbody></table></div>}</section></>;
}

function normalizeItem(raw: any): ImportItem { const list = (value: unknown) => Array.isArray(value) ? value.map(String).filter(Boolean) : String(value || "").split("|").map(item => item.trim()).filter(Boolean); return { companyCode: String(raw.companyCode || raw.societe || "").trim().toUpperCase(), jobCode: String(raw.jobCode || raw.codePoste || "").trim().toUpperCase(), jobTitle: String(raw.jobTitle || raw.intitule || raw.poste || "").trim(), direction: text(raw.direction), department: text(raw.department || raw.departement), service: text(raw.service), hierarchicalReporting: text(raw.hierarchicalReporting || raw.rattachement), mission: text(raw.mission), missions: list(raw.missions), responsibilities: list(raw.responsibilities || raw.responsabilites), kpis: list(raw.kpis || raw.KPI), profile: text(raw.profile || raw.profil) }; }
function parseOrganizationManual(raw: string): ImportItem[] {
  const lines = raw.split(/\r?\n/).map(value => value.trim()).filter(Boolean);
  const results: ImportItem[] = []; let direction = "";
  for (let index = 0; index < lines.length; index += 1) {
    if (/^2\.\d+\s+/.test(lines[index])) { direction = lines[index].replace(/^2\.\d+\s+/, ""); continue; }
    if (marker(lines[index]) !== "rattache a" || index === 0) continue;
    const title = lines[index - 1];
    if (!title || /^\d+(?:\.\d+)*\s/.test(title)) continue;
    const reporting = lines[index + 1] || ""; let cursor = index + 2; let mission = ""; const responsibilities: string[] = []; const kpis: string[] = []; let profile = "";
    if (marker(lines[cursor]) === "mission du poste") { mission = lines[cursor + 1] || ""; cursor += 2; }
    if (marker(lines[cursor]).startsWith("responsabilites principal")) { cursor += 1; while (cursor < lines.length && marker(lines[cursor]) !== "kpi cles") responsibilities.push(lines[cursor++]); }
    if (marker(lines[cursor]) === "kpi cles") { cursor += 1; while (cursor < lines.length && !marker(lines[cursor]).startsWith("profil recherche") && marker(lines[cursor]) !== "rattache a" && !/^2\.\d+\s+/.test(lines[cursor])) kpis.push(...splitValues(lines[cursor++])); }
    if (marker(lines[cursor]).startsWith("profil recherche")) profile = lines[cursor].replace(/^Profil recherché\s*:\s*/i, "");
    results.push({ jobCode: uniqueJobCode(title, results), jobTitle: title, direction: direction || undefined, hierarchicalReporting: reporting, mission, responsibilities, kpis, profile });
  }
  return results;
}
function marker(value = "") { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim(); }
function splitValues(value: string) { return value.split(/[,;]/).map(item => item.trim()).filter(Boolean); }
function uniqueJobCode(title: string, rows: ImportItem[]) { const base = title.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_|_$/g, "").slice(0, 70) || "POSTE"; let code = base; let suffix = 2; const used = new Set(rows.map(row => row.jobCode)); while (used.has(code)) code = `${base.slice(0, 66)}_${suffix++}`; return code; }
function text(value: unknown) { return String(value || "").trim() || undefined; }
function parseCsv(textValue: string) { const rows = textValue.replace(/^\uFEFF/, "").split(/\r?\n/).filter(line => line.trim()).map(parseCsvLine); if (rows.length < 2) return []; const headers = rows[0].map(value => value.trim()); return rows.slice(1).map(values => Object.fromEntries(headers.map((header, index) => [header, values[index] || ""]))); }
function parseCsvLine(line: string) { const values: string[] = []; let value = ""; let quoted = false; for (let index = 0; index < line.length; index += 1) { const char = line[index]; if (char === '"' && quoted && line[index + 1] === '"') { value += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if ((char === "," || char === ";") && !quoted) { values.push(value); value = ""; } else value += char; } values.push(value); return values; }
function label(status: Preview["status"]) { return ({ CREATE: "Nouveau poste", ADD_TEMPLATE: "Ajouter le modèle", DUPLICATE: "Doublon ignoré", INVALID_COMPANY: "Société inconnue" } as const)[status]; }
function clean(reason: unknown) { const value = reason instanceof Error ? reason.message : "Opération impossible."; try { const body = JSON.parse(value); return Array.isArray(body.message) ? body.message.join(" · ") : body.message || value; } catch { return value; } }
