import { Archive, Download, FileCheck2, GitCompareArrows, Pencil, Printer, Send, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Button } from "../components/Button";
import { JobDescriptionA4Preview } from "../components/JobDescriptionA4Preview";
import { LoadingState } from "../components/LoadingState";
import { PageHeader } from "../components/PageHeader";
import { StatusBadge } from "../components/StatusBadge";
import { api, fileUrl } from "../lib/api";
import { useAuth } from "../lib/auth";
import { JobPosition } from "../lib/types";
import { useApi } from "../lib/useApi";

type ArchivedFile = { id: string; originalName: string; sizeBytes: number; sha256: string; generatedAt: string; generatedBy?: { fullName: string } };
type Version = { id: string; majorVersion: number; minorVersion: number; status: string; revisionReason?: string | null; createdAt?: string; files: ArchivedFile[] };
type Approval = { id: string; status: string; comment: string | null; reviewedAt: string | null; workflowStep: { stepOrder: number; label: string }; reviewedBy: { fullName: string } | null };
type DocumentDetail = { id: string; reference: string; status: string; effectiveDate?: string | null; employee: { fullName: string }; company: any; jobPosition: JobPosition | null; currentVersion: Version & { content: any; employeeSnapshot: any; jobSnapshot: any; approvals: Approval[] }; versions: Version[] };
type CompareResult = { from: Version; to: Version; changes: Array<{ path: string; before: unknown; after: unknown; type: string }> };
const previewVariables = [{ code: "employee.full_name", sample: "Nom et prénom" }, { code: "employee.matricule", sample: "Matricule" }, { code: "company.name", sample: "Société" }, { code: "document.reference", sample: "Référence" }, { code: "document.version", sample: "V1.0" }, { code: "document.effective_date", sample: "Date d'effet" }, { code: "manager.full_name", sample: "Responsable hiérarchique" }];

export function JobDescriptionDocumentPage() {
  const { id } = useParams(); const { can } = useAuth(); const request = useApi<DocumentDetail | null>(id ? `/api/job-descriptions/documents/${id}` : null, null);
  const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [finishOpen, setFinishOpen] = useState(false); const [action, setAction] = useState<"revise" | "archive" | null>(null); const [reason, setReason] = useState(""); const [bump, setBump] = useState<"MINOR" | "MAJOR">("MINOR"); const [compareOpen, setCompareOpen] = useState(false); const [fromId, setFromId] = useState(""); const [toId, setToId] = useState(""); const [comparison, setComparison] = useState<CompareResult | null>(null);
  const row = request.data;
  const position = useMemo(() => { if (!row) return null; const snapshot = row.currentVersion.jobSnapshot || {}; return row.jobPosition ? { ...row.jobPosition, company: row.company } : ({ id: "snapshot", code: snapshot.selected?.jobCode || "-", title: snapshot.selected?.jobTitle || "Poste personnalisé", direction: null, department: null, service: null, hierarchicalReporting: null, functionalReporting: null, isActive: true, companyId: row.company.id, company: row.company, aliases: [], templates: [] } as JobPosition); }, [row]);
  async function run(path: string, body?: unknown, success?: string) { setBusy(true); try { await api(path, { method: "POST", body: body ? JSON.stringify(body) : undefined }); setMessage(success || "Opération effectuée."); setError(null); setAction(null); setFinishOpen(false); setReason(""); request.reload(); } catch (cause) { setError(clean(cause)); } finally { setBusy(false); } }
  async function compare() { if (!id || !fromId || !toId) return; setBusy(true); try { setComparison(await api(`/api/job-descriptions/documents/${id}/compare?from=${fromId}&to=${toId}`)); setError(null); } catch (cause) { setError(clean(cause)); } finally { setBusy(false); } }
  if (request.loading) return <LoadingState label="Chargement de la fiche de poste..." />;
  if (!row || !position) return <div className="alert alert-error">Fiche de poste introuvable.</div>;
  const variables = [...previewVariables, { code: "employee.full_name", sample: row.currentVersion.employeeSnapshot?.fullName || row.employee.fullName }, { code: "employee.matricule", sample: row.currentVersion.employeeSnapshot?.matricule || "-" }, { code: "company.name", sample: row.company.shortName }, { code: "document.reference", sample: row.reference }];
  return <>
    <PageHeader title={`${row.reference} — ${row.employee.fullName}`} backTo="/job-descriptions/validation" backLabel="Validations" actions={<div className="row-actions"><StatusBadge value={row.status} /><Button variant="secondary" onClick={() => window.print()}><Printer size={15} /> Imprimer</Button>{row.currentVersion.status === "DRAFT" && can("job_description.edit") && <Link className="btn btn-primary" to={`/job-descriptions/documents/${row.id}/builder`}><Pencil size={15} /> Personnaliser</Link>}{row.currentVersion.status === "DRAFT" && can("job_description.edit") && <Button variant="primary" disabled={busy} onClick={() => run(`/api/job-descriptions/documents/${id}/submit`, undefined, "Fiche envoyée dans le circuit de validation.")}><Send size={15} /> Soumettre</Button>}{row.currentVersion.status === "VALIDATED" && can("job_description.edit") && <Button variant="secondary" onClick={() => setAction("revise")}><Pencil size={15} /> Réviser</Button>}{row.currentVersion.status === "VALIDATED" && !row.currentVersion.files.length && can("job_description.generate") && <Button variant="primary" onClick={() => setFinishOpen(true)}><FileCheck2 size={15} /> Finaliser & Générer</Button>}{row.status !== "ARCHIVED" && can("job_description.archive") && <Button variant="danger" onClick={() => setAction("archive")}><Archive size={15} /> Archiver</Button>}</div>} />
    {message && <div className="alert alert-success">{message}</div>}{error && <div className="alert alert-error">{error}</div>}
    <div className="job-document-review-layout"><section className="job-document-preview"><JobDescriptionA4Preview document={row.currentVersion.content} position={position} templateName={position.title} variables={variables} zoom={.75} /></section><aside className="job-approval-history"><h2>Circuit de validation</h2>{row.currentVersion.approvals.length ? row.currentVersion.approvals.sort((a, b) => a.workflowStep.stepOrder - b.workflowStep.stepOrder).map(approval => <div key={approval.id} className={`approval-history-step ${approval.status.toLowerCase()}`}><b>{approval.workflowStep.stepOrder}</b><span><strong>{approval.workflowStep.label}</strong><small>{approval.status === "APPROVED" ? `Validé par ${approval.reviewedBy?.fullName || "-"}` : approval.status === "REJECTED" ? `Refusé par ${approval.reviewedBy?.fullName || "-"}` : approval.status === "CANCELLED" ? "Annulée" : "En attente"}</small>{approval.comment && <em>{approval.comment}</em>}</span></div>) : <p className="muted">La fiche n'est pas encore soumise.</p>}<h2>Documents archivés</h2>{row.currentVersion.files.length ? row.currentVersion.files.map(file => <a className="job-archive-file" key={file.id} href={fileUrl(`/api/job-descriptions/files/${file.id}/download`, new URLSearchParams())}><FileCheck2 size={17} /><span><strong>{file.originalName}</strong><small>{formatSize(file.sizeBytes)} · {new Date(file.generatedAt).toLocaleString("fr-FR")}</small><em>SHA-256 {file.sha256.slice(0, 12)}…</em></span><Download size={16} /></a>) : <p className="muted">Aucun PDF officiel archivé.</p>}<div className="version-heading"><h2>Versions</h2>{row.versions.length > 1 && <button onClick={() => { setFromId(row.versions[1]?.id || ""); setToId(row.versions[0]?.id || ""); setCompareOpen(true); }}><GitCompareArrows size={14} /> Comparer</button>}</div>{row.versions.map(version => <div key={version.id} className="document-version-row"><span><b>V{version.majorVersion}.{version.minorVersion}</b>{version.revisionReason && <small>{version.revisionReason}</small>}</span><StatusBadge value={version.status} />{version.files.length > 0 && <FileCheck2 size={14} />}</div>)}</aside></div>
    {finishOpen && <Modal title="Finaliser & Générer" onClose={() => setFinishOpen(false)}><p>Vérifiez le résumé avant de créer l'archive PDF immuable.</p><dl className="wizard-summary"><div><dt>Employé</dt><dd>{row.employee.fullName}</dd></div><div><dt>Société</dt><dd>{row.company.shortName}</dd></div><div><dt>Poste</dt><dd>{position.title}</dd></div><div><dt>Référence</dt><dd>{row.reference}</dd></div><div><dt>Version</dt><dd>V{row.currentVersion.majorVersion}.{row.currentVersion.minorVersion}</dd></div><div><dt>Missions</dt><dd>{missionCount(row.currentVersion.content)}</dd></div></dl><footer><Button variant="secondary" onClick={() => setFinishOpen(false)}>Retour</Button><Button variant="primary" disabled={busy} onClick={() => run(`/api/job-descriptions/documents/${id}/generate-pdf`, undefined, "PDF officiel généré et archivé.")}><FileCheck2 size={15} /> {busy ? "Génération..." : "Finaliser & Générer"}</Button></footer></Modal>}
    {action && <Modal title={action === "revise" ? "Créer une révision" : "Archiver la fiche"} onClose={() => setAction(null)}>{action === "revise" && <label className="filter-field"><span>Nouvelle version</span><select value={bump} onChange={event => setBump(event.target.value as any)}><option value="MINOR">Mineure — V{row.currentVersion.majorVersion}.{row.currentVersion.minorVersion + 1}</option><option value="MAJOR">Majeure — V{row.currentVersion.majorVersion + 1}.0</option></select></label>}<label className="filter-field"><span>Motif obligatoire</span><textarea rows={4} value={reason} onChange={event => setReason(event.target.value)} /></label><footer><Button variant="ghost" onClick={() => setAction(null)}>Annuler</Button><Button variant={action === "archive" ? "danger" : "primary"} disabled={busy || !reason.trim()} onClick={() => run(action === "revise" ? `/api/job-descriptions/documents/${id}/revise` : `/api/job-descriptions/documents/${id}/archive`, action === "revise" ? { bump, reason } : { reason }, action === "revise" ? "Nouvelle version brouillon créée." : "Fiche archivée.")}>{action === "revise" ? "Créer la version" : "Confirmer l'archivage"}</Button></footer></Modal>}
    {compareOpen && <Modal title="Comparer les versions" onClose={() => setCompareOpen(false)} wide><div className="version-compare-picker"><select value={fromId} onChange={event => setFromId(event.target.value)}>{row.versions.map(version => <option key={version.id} value={version.id}>V{version.majorVersion}.{version.minorVersion}</option>)}</select><GitCompareArrows size={17} /><select value={toId} onChange={event => setToId(event.target.value)}>{row.versions.map(version => <option key={version.id} value={version.id}>V{version.majorVersion}.{version.minorVersion}</option>)}</select><Button variant="primary" disabled={busy || fromId === toId} onClick={compare}>Comparer</Button></div>{comparison && <div className="version-diff-list">{comparison.changes.length ? comparison.changes.slice(0, 200).map((change, index) => <div key={`${change.path}-${index}`}><code>{humanPath(change.path)}</code><span className="before">{display(change.before)}</span><span>→</span><span className="after">{display(change.after)}</span></div>) : <div className="empty-state">Les deux versions sont identiques.</div>}</div>}</Modal>}
  </>;
}

function Modal({ title, onClose, wide, children }: { title: string; onClose: () => void; wide?: boolean; children: React.ReactNode }) { return <div className="modal-backdrop"><section className={`modal-card job-finish-modal ${wide ? "wide" : ""}`}><header><h2>{title}</h2><button className="icon-button" onClick={onClose}><X size={18} /></button></header>{children}</section></div>; }
function missionCount(content: any) { return (content?.blocks || []).filter((block: any) => block.visible && block.type === "TASKS").reduce((total: number, block: any) => total + (Array.isArray(block.content?.items) ? block.content.items.length : 0), 0); }
function formatSize(bytes: number) { return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} Ko` : `${(bytes / 1024 / 1024).toFixed(1)} Mo`; }
function clean(cause: unknown) { const value = cause instanceof Error ? cause.message : "Opération impossible."; try { const body = JSON.parse(value); return Array.isArray(body.message) ? body.message.join(" · ") : body.message || value; } catch { return value; } }
function display(value: unknown) { if (value === undefined) return "—"; if (typeof value === "object") return JSON.stringify(value).slice(0, 220); return String(value); }
function humanPath(path: string) { return path.replace(/^content\./, "").replace(/\.content\.text/g, " — contenu").replace(/\.title/g, " — titre"); }
