import { Eye, Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { DataTable } from "../components/DataTable";
import { PageHeader } from "../components/PageHeader";
import { StatusBadge } from "../components/StatusBadge";
import { useAuth } from "../lib/auth";
import { useApi } from "../lib/useApi";

type Row = { id: string; reference: string; status: string; effectiveDate: string | null; employee: { fullName: string; localMatricule?: string | null; employeeCode: string }; company: { shortName: string }; jobPosition: { title: string } | null; currentVersion: { majorVersion: number; minorVersion: number } | null };

export function JobDescriptionDocumentsPage() {
  const { can } = useAuth(); const [params] = useSearchParams(); const employeeId = params.get("employeeId") || ""; const request = useApi<Row[]>(`/api/job-descriptions/documents${employeeId ? `?employeeId=${encodeURIComponent(employeeId)}` : ""}`, []); const [search, setSearch] = useState(""); const [status, setStatus] = useState("");
  const rows = useMemo(() => request.data.filter(row => (!status || row.status === status) && (!search.trim() || `${row.reference} ${row.employee.fullName} ${row.employee.localMatricule || row.employee.employeeCode} ${row.jobPosition?.title || ""}`.toLowerCase().includes(search.toLowerCase()))), [request.data, search, status]);
  return <><PageHeader title="Fiches individuelles" backTo="/job-descriptions" backLabel="Bibliothèque" actions={can("job_description.create") && <Link className="btn btn-primary" to="/job-descriptions/new"><Plus size={15} /> Nouvelle fiche</Link>} /><section className="panel"><div className="library-toolbar"><div className="input-icon library-search"><Search size={15} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Employé, matricule, référence, poste..." /></div><select value={status} onChange={event => setStatus(event.target.value)}><option value="">Tous les statuts</option><option value="DRAFT">Brouillon</option><option value="PENDING_APPROVAL">À valider</option><option value="VALIDATED">Validée</option><option value="REJECTED">Rejetée</option><option value="ARCHIVED">Archivée</option></select></div><DataTable rows={rows} loading={request.loading} pageSize={25} empty="Aucune fiche individuelle." columns={[{ key: "employee", header: "Employé", render: row => <div className="job-title-cell"><strong>{row.employee.fullName}</strong><span>{row.employee.localMatricule || row.employee.employeeCode}</span></div>, sortValue: row => row.employee.fullName }, { key: "reference", header: "Référence", render: row => <span className="job-code-chip">{row.reference}</span>, sortValue: row => row.reference }, { key: "company", header: "Société", render: row => row.company.shortName }, { key: "job", header: "Poste", render: row => row.jobPosition?.title || "Poste personnalisé" }, { key: "version", header: "Version", render: row => row.currentVersion ? `V${row.currentVersion.majorVersion}.${row.currentVersion.minorVersion}` : "-" }, { key: "effect", header: "Date d'effet", render: row => row.effectiveDate ? new Date(row.effectiveDate).toLocaleDateString("fr-FR") : "-" }, { key: "status", header: "Statut", render: row => <StatusBadge value={row.status} /> }, { key: "actions", header: "Actions", render: row => <Link className="btn btn-ghost" to={`/job-descriptions/documents/${row.id}`}><Eye size={14} /> Voir</Link> }]} /></section></>;
}
